import type { Metadata } from "next";
import { Stint_Ultra_Condensed } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import Toaster from "@/components/ToastContainer";
const MriyaGrotesk = localFont({
  src: "../public/fonts/MriyaGrotesk-ExtraBold.ttf",
  variable: "--font-MriyaGrotesk",
  weight: "900",
});
const Stint = Stint_Ultra_Condensed({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-Stint",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${MriyaGrotesk.variable} ${Stint.variable} Black-orange-bg `}
        suppressHydrationWarning
      >
        <Toaster />
        <div className="font-MriyaGrotesk font-[900]">{children}</div>
      </body>
    </html>
  );
}
